#format can be "text" or "json" for different output (human or machine readable)
format: 'text'
#checkAsserts checks assertions
checkAsserts: true
#coverage controls coverage guided testing
coverage: false
#seqLen defines how many transactions are in a test sequence
seqLen: 1
#testLimit is the number of test sequences to run
testLimit: 500000
