name: Comment commands
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  mythx_partial:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    outputs:
      run: ${{ steps.check.outputs.triggered }}
      mode: ${{ steps.mode.outputs.moode }}
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '/mythx partial'
          prefix_only: true
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Get mode
        id: mode
        run: |
          mode=$(echo "${{ github.event.comment }}"" | sed "s|/mythx partial ||" | sed "s/ //")
          echo "::set-output name=mode::$mode"
  mythx_partial_run:
    needs: ['mythx_partial']
    if: ${{ needs.mythx_partial.outputs.run }}
    uses: './.github/workflows/mythx-changed.yml'
    with:
      pr_number: ${{ github.event.issue.number }}
      mode: $ {{ needs.mythx_partial.outputs.mode }}
    secrets: inherit

  mythx_full:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    outputs:
      run: ${{ steps.check.outputs.triggered }}
      mode: ${{ steps.mode.outputs.moode }}
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '/mythx full'
          prefix_only: true
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Get mode
        id: mode
        run: |
          mode=$(echo "${{ github.event.comment }}"" | sed "s|/mythx full ||" | sed "s/ //")
          echo "::set-output name=mode::$mode"
  mythx_full_run:
    needs: ['mythx_full']
    if: ${{ needs.mythx_full.outputs.run }}
    uses: './.github/workflows/mythx-full.yml'
    with:
      mode: $ {{ needs.mythx_full.outputs.mode }}
    secrets: inherit



  release_label:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '/release'
          prefix_only: true
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Get type
        id: type
        run: |
          type=$(echo "${{ github.event.comment }}"" | sed "s|/release ||" | sed "s/ //")
          echo "::set-output name=type::$type"
      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: release:${{ steps.type.outputs.type }}

  subgraph_label:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '/subgraph'
          prefix_only: true
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Get type
        id: type
        run: |
          type=$(echo "${{ github.event.comment }}"" | sed "s|/subgraph ||" | sed "s/ //")
          echo "::set-output name=type::$type"
      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: subgraph:${{ steps.type.outputs.type }}