name: Contracts Tests
on:
  push:
    branches:
      - main
    paths:
      - 'packages/contracts/**'
      - '.github/workflows/contract-*.yml'
  pull_request:
    paths:
      - 'packages/contracts/**'
      - '.github/workflows/contract-*.yml'
  workflow_dispatch:

env:
  working-directory: packages/contracts

jobs:
  test-hardhat:
    if: github.actor != 'arabot-1'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    env:
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: 18
      - name: Install dependencies
        run: cd ../../ && yarn install --pure-lockfile
      - name: Compile contracts
        run: yarn run build && yarn run build:npm
      - name: Run Hardhat Tests
        env:
          REPORT_GAS: true
          HARDHAT_DAO_ENS_DOMAIN: 'dao.eth'
          HARDHAT_PLUGIN_ENS_DOMAIN: 'plugin.dao.eth'
          MANAGEMENT_DAO_SUBDOMAIN: 'management'
          MANAGEMENT_DAO_MULTISIG_LISTEDONLY: ${{ vars.MANAGEMENT_DAO_MULTISIG_LISTEDONLY }}
          MANAGEMENT_DAO_MULTISIG_APPROVERS: ${{ vars.MANAGEMENT_DAO_MULTISIG_APPROVERS }}
          MANAGEMENT_DAO_MULTISIG_MINAPPROVALS: ${{ vars.MANAGEMENT_DAO_MULTISIG_MINAPPROVALS }}
        run: yarn run test
      - name: Run solidity-docgen
        run: yarn run docgen
