name: Contracts Tests
on:
  push:
    paths:
      - 'packages/contracts/**'
      - '.github/workflows/contract-*.yml'

env:
  working-directory: packages/contracts

jobs:
  test-hardhat:
    if: github.actor != 'arabot-1'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 16
      - name: Install dependencies
        run: cd ../../ && yarn install --pure-lockfile
      - name: Check formatting
        run: yarn run formatting:check
      - name: Compile contracts
        run: yarn run build && yarn run build:npm
      - name: Run Hardhat Tests
        env:
          REPORT_GAS: true
          ETH_KEY: ''
          HARDHAT_DAO_ENS_DOMAIN: 'dao.eth'
          HARDHAT_PLUGIN_ENS_DOMAIN: 'plugin.dao.eth'
          MANAGINGDAO_SUBDOMAIN: 'aragon-management'
        run: yarn run test
      - name: Run solidity-docgen
        run: yarn run docgen
